using System;

/*
Even Fibonacci numbers
Problem 2 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

namespace Euler2
{
    class Program
    {
        static void Main(string[] args)
        {
            int count = 0;
            int fib = 1;
            int prevFib = 1;
            int tempFib;
            while (fib <= 4000000)
            {
                tempFib = fib;
                fib += prevFib;
                prevFib = tempFib;
                if (fib % 2 == 0)
                    count += fib;
            }
            Console.WriteLine(count);
        }
    }
}
